function Donnee(key, count) {
    let pictureCharacter = ["https://d1u1mce87gyfbn.cloudfront.net/hero/ana/hero-select-portrait.png", "https://d1u1mce87gyfbn.cloudfront.net/hero/ashe/hero-select-portrait.png", "https://d1u1mce87gyfbn.cloudfront.net/hero/bastion/hero-select-portrait.png", "https://d1u1mce87gyfbn.cloudfront.net/hero/brigitte/hero-select-portrait.png", "https://d1u1mce87gyfbn.cloudfront.net/hero/dva/hero-select-portrait.png", "https://d1u1mce87gyfbn.cloudfront.net/hero/doomfist/hero-select-portrait.png", "https://d1u1mce87gyfbn.cloudfront.net/hero/genji/hero-select-portrait.png", "https://d1u1mce87gyfbn.cloudfront.net/hero/hanzo/hero-select-portrait.png", "https://d1u1mce87gyfbn.cloudfront.net/hero/junkrat/hero-select-portrait.png", "https://d1u1mce87gyfbn.cloudfront.net/hero/lucio/hero-select-portrait.png", "https://d1u1mce87gyfbn.cloudfront.net/hero/mccree/hero-select-portrait.png", "https://d1u1mce87gyfbn.cloudfront.net/hero/mei/hero-select-portrait.png", "https://d1u1mce87gyfbn.cloudfront.net/hero/mercy/hero-select-portrait.png", "https://d1u1mce87gyfbn.cloudfront.net/hero/moira/hero-select-portrait.png", "https://d1u1mce87gyfbn.cloudfront.net/hero/orisa/hero-select-portrait.png", "https://d1u1mce87gyfbn.cloudfront.net/hero/pharah/hero-select-portrait.png", "https://d1u1mce87gyfbn.cloudfront.net/hero/reaper/hero-select-portrait.png", "https://d1u1mce87gyfbn.cloudfront.net/hero/reinhardt/hero-select-portrait.png", "https://d1u1mce87gyfbn.cloudfront.net/hero/roadhog/hero-select-portrait.png", "https://d1u1mce87gyfbn.cloudfront.net/hero/soldier-76/hero-select-portrait.png", "https://d1u1mce87gyfbn.cloudfront.net/hero/sombra/hero-select-portrait.png", "https://d1u1mce87gyfbn.cloudfront.net/hero/symmetra/hero-select-portrait.png", "https://d1u1mce87gyfbn.cloudfront.net/hero/torbjorn/hero-select-portrait.png", "https://d1u1mce87gyfbn.cloudfront.net/hero/tracer/hero-select-portrait.png", "https://d1u1mce87gyfbn.cloudfront.net/hero/widowmaker/hero-select-portrait.png", "https://d1u1mce87gyfbn.cloudfront.net/hero/winston/hero-select-portrait.png", "https://d1u1mce87gyfbn.cloudfront.net/hero/wrecking-ball/hero-select-portrait.png", "https://d1u1mce87gyfbn.cloudfront.net/hero/zarya/hero-select-portrait.png", "https://d1u1mce87gyfbn.cloudfront.net/hero/zenyatta/hero-select-portrait.png"];
    let nameCharacter = ["Ana", "Ashe", "Bastion", "Brigitte", "D-va", "Doomfist", "Genji", "Hanzo", "Chacal", "Lucio", "McCree", "Mei", "Ange", "Moira", "Orisa", "Pharah", "Faucheur", "Reinhardt", "Chopper", "Soldat : 76", "Sombra", "Symmetra", "Torbjörn", "Tracer", "Fatal", "Winston", "Bouldozer", "Zarya", "Zenyatta"]
    if (key === "pictureCharacter") {
        return pictureCharacter[count];
    }
    else if (key === "nameCharacter") {
        return nameCharacter[count];
    }

}
export default Donnee;