import React from 'react'
import {
    ThemeProvider,
    CSSReset,
    theme,
    Button,
    Flex,
    Icon,
    InputGroup,
    InputLeftAddon,
    Input,
    InputRightElement,
    Text
} from '@chakra-ui/core'
import { Link } from 'react-router-dom'

const Register = () => (
    <ThemeProvider theme={theme}>
        <CSSReset />
        <Flex
            display="flex"
            flexDirection="row"
            alignItems="center"
            justifyContent="center"
            textAlign="center"
            backgroundColor="gray.100"
            p={5}
            overflow="visible"
            width="100%"
            height="25%"
        >
            <Flex
                flexDirection="row"
                justifyContent="flex-start"
                alignItems="center"
                width="46%"
                height="100%"
            >
                <Link to="/">
                    <Button
                        display="flex"
                        flexDirection="row"
                        justifyContent="center"
                        alignItems="center"
                        textAlign="center"
                        backgroundColor="orange.300"
                        color="whiteAlpha.900"
                        letterSpacing="widest"
                        h="50px"
                        w="50%"
                        borderRadius="10px"
                        fontSize="100%"
                        size="md"
                        variantColor="yellow"
                        leftIcon="arrow-back"
                        m={3}
                        pl={10}
                        pr={10}
                    >
                        Back
          </Button>
                </Link>
            </Flex>
            <Flex
                justifyContent="center"
                alignItems="center"
                width="54%"
                height="100%"
            >
                <Text
                    display="flex"
                    justifyContent="flex-start"
                    alignItems="center"
                    width="100%"
                    height="100%"
                    color="orange.300"
                    fontSize="5xl"
                    fontFamily="Bangers"
                >
                    Register
        </Text>
            </Flex>
        </Flex>
        <Flex
            flexDirection="row"
            justifyContent="center"
            backgroundColor="facebook.900"
            h="100%"
            w="100%"
            pt={10}
            pb={10}
            pl={5}
            pr={5}
        >
            <Flex
                flexDirection="column"
                h="100%"
                w="100%"
            >
                <InputGroup
                    w="100%"
                    alignContent
                >
                    <InputLeftAddon
                        fontStyle="italic"
                        width="30%"
                        justifyContent="center"
                        color="orange.300"
                        backgroundColor="facebook.300"
                        letterSpacing="widest"
                    >
                        Username:
                </InputLeftAddon>
                    <Input
                        fontSize="sm"
                        placeholder="Type your username"
                        letterSpacing="widest"
                        lineHeight="tall"
                        w="70%"
                    />
                    <InputRightElement>
                        <Icon
                            name="star"
                            color="orange.300"
                        />
                    </InputRightElement>
                </InputGroup>
                <InputGroup
                    mt={10}
                >
                    <InputLeftAddon
                        color="orange.300"
                        backgroundColor="facebook.300"
                        width="30%"
                        justifyContent="center"
                        letterSpacing="widest"
                    >
                        E-mail:
                </InputLeftAddon>
                    <Input
                        fontSize="sm"
                        placeholder="Type your e-mail"
                        letterSpacing="widest"
                        lineHeight="tall"
                        w="70%" />
                    <InputRightElement>
                        <Icon
                            name="email"
                            color="orange.300"
                        />
                    </InputRightElement>
                </InputGroup>
                <InputGroup
                    mt={10}
                    textAlign="left"
                    fontStyle="italic"
                    letterSpacing="wide"
                    w="100%"
                >
                    <InputLeftAddon
                        color="orange.300"
                        backgroundColor="facebook.300"
                        width="30%"
                        justifyContent="center"
                        letterSpacing="widest"
                    >
                        Password:
                </InputLeftAddon>
                    <Input
                        fontSize="sm"
                        placeholder="Type your password"
                        letterSpacing="widest"
                        lineHeight="tall"
                        w="70%"
                    />
                    <InputRightElement>
                        <Icon
                            name="lock"
                            color="orange.300"
                        />
                    </InputRightElement>
                </InputGroup>
                <Flex
                    flexDirection="row"
                    justifyContent="center"
                    h="100%"
                    w="100%"
                >
                    <Button
                        flexDirection="row"
                        justifyContent="center"
                        textAlign="center"
                        color="whiteAlpha.900"
                        backgroundColor="orange.300"
                        mt={10}
                        display="flex"
                        rightIcon="arrow-forward"
                        borderRadius={10}
                        pr={2}
                        variant="solid"
                        w="50%"
                        letterSpacing="widest"
                        variantColor="yellow"
                    >
                        Create
        </Button>
                </Flex>
            </Flex>
        </Flex>
    </ThemeProvider >
)

export default Register
